multi:
  sample_num: 10
  debug:
    max_new_tokens: 512
    temperature: 1.0
    top_k: 50
    top_p: 0.95
    do_sample: true
    num_return_sequences: 10

codeT:
  base:
    temperature: 0.0
    top_p: 1.0
  debug:
    max_gen: 512
    temperature: 1.0
    top_p: 0.95
